### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by getsueineko** [nomadturk/vpn-adblock#1]
Cool Project!
But can you help or write **detail article how to get** and add IPv6 range? Howto IPv6 for noobs, please!

**Comment by nomadturk** [comment]
Hey @getsueineko 

I don't think I'm your guy if you want a detailed article on how to get and add an IPv6 range.
Especially if your provider doesn't allocate any IPv6 to you. You can get a HE.net IPv6 tunnel easily and there are already many tutorials written about the subject.

Such as:
https://www.linode.com/docs/networking/set-up-an-ipv6-tunnel-on-your-linode
https://fedoraproject.org/wiki/IPv6_tunnel_via_Hurricane_Electric
http://teamarin.net/2014/12/15/set-ipv6-home/
https://wiki.archlinux.org/index.php/IPv6_tunnel_broker_setup
...

IPv6 is a confusing matter for many but there are already some good resources out there. The links above were the result of a 5-second google search after all...
